---
title: "Creating graphs in R with `ggplot2`"
author: "Erin Aylsworth"
date: '2023-01-08'
output: html_document
---

# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.

```{r}
library(tidyverse)
library(readxl)
library(here)
```

In this session, we'll use data for parks visitation from two files:
ca_np.csv
ci_np.xlsx

```{r}
ca_np <- read_csv(here("data", "ca_np.csv"))
```

```{r}
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

5.4 Our first ggplot graph: Visitors to Channel Islands NP

Here is the base plot, from which we can customize.

```{r}
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))
```

5.5 Intro to customizing ggplot graphs

```{r}
gg_base +
        geom_line(linetype = "dotted") +
        theme_bw() +
        labs(
                x = "Year",
                y = "Annual park visitors",
                title = "Channel Islands NP Visitation",
                subtitle = "(1963 - 2016)"
        )
```

5.11 Faceting

```{r}
ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +
        geom_line(show.legend = FALSE) +
        theme_light() +
        labs(x = "year", y = "annual visitors") +
        facet_wrap(~ park_name)

ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
```